// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/purchasing": {
    params: {};
  };
  "/purchasing/:id": {
    params: {
      "id": string;
    };
  };
  "/purchasing/:id/transition": {
    params: {
      "id": string;
    };
  };
  "/purchasing/:id/receive": {
    params: {
      "id": string;
    };
  };
  "/purchasing/:id/lines": {
    params: {
      "id": string;
    };
  };
  "/purchasing/new": {
    params: {};
  };
  "/customers": {
    params: {};
  };
  "/customers/:id": {
    params: {
      "id": string;
    };
  };
  "/customers/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/customers/new": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/inventory/export": {
    params: {};
  };
  "/inventory/:id": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/movements": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/lots": {
    params: {
      "id": string;
    };
  };
  "/inventory/new": {
    params: {};
  };
  "/suppliers": {
    params: {};
  };
  "/suppliers/:id": {
    params: {
      "id": string;
    };
  };
  "/suppliers/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/suppliers/new": {
    params: {};
  };
  "/planning": {
    params: {};
  };
  "/planning/purchasing": {
    params: {};
  };
  "/planning/materials": {
    params: {};
  };
  "/planning/packaging": {
    params: {};
  };
  "/planning/schedule": {
    params: {};
  };
  "/planning/summary": {
    params: {};
  };
  "/planning/demand": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/batches": {
    params: {};
  };
  "/batches/export": {
    params: {};
  };
  "/batches/:id": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/fermentation": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/consumption": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/transition": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/packaging": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/quality": {
    params: {
      "id": string;
    };
  };
  "/batches/new": {
    params: {};
  };
  "/recipes": {
    params: {};
  };
  "/recipes/import": {
    params: {};
  };
  "/recipes/:id": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/ingredients": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/versions": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/process": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/clone": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/recipes/new": {
    params: {};
  };
  "/vessels": {
    params: {};
  };
  "/vessels/:id": {
    params: {
      "id": string;
    };
  };
  "/vessels/new": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/orders/export": {
    params: {};
  };
  "/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/orders/:id/transition": {
    params: {
      "id": string;
    };
  };
  "/orders/:id/invoice": {
    params: {
      "id": string;
    };
  };
  "/orders/:id/lines": {
    params: {
      "id": string;
    };
  };
  "/orders/:id/pick": {
    params: {
      "id": string;
    };
  };
  "/orders/new": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/stock": {
    params: {};
  };
  "/stock/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/purchasing" | "/purchasing/:id" | "/purchasing/:id/transition" | "/purchasing/:id/receive" | "/purchasing/:id/lines" | "/purchasing/new" | "/customers" | "/customers/:id" | "/customers/:id/edit" | "/customers/new" | "/inventory" | "/inventory/export" | "/inventory/:id" | "/inventory/:id/movements" | "/inventory/:id/edit" | "/inventory/:id/lots" | "/inventory/new" | "/suppliers" | "/suppliers/:id" | "/suppliers/:id/edit" | "/suppliers/new" | "/planning" | "/planning/purchasing" | "/planning/materials" | "/planning/packaging" | "/planning/schedule" | "/planning/summary" | "/planning/demand" | "/settings" | "/batches" | "/batches/export" | "/batches/:id" | "/batches/:id/fermentation" | "/batches/:id/consumption" | "/batches/:id/transition" | "/batches/:id/packaging" | "/batches/:id/quality" | "/batches/new" | "/recipes" | "/recipes/import" | "/recipes/:id" | "/recipes/:id/ingredients" | "/recipes/:id/versions" | "/recipes/:id/process" | "/recipes/:id/clone" | "/recipes/:id/edit" | "/recipes/new" | "/vessels" | "/vessels/:id" | "/vessels/new" | "/logout" | "/orders" | "/orders/export" | "/orders/:id" | "/orders/:id/transition" | "/orders/:id/invoice" | "/orders/:id/lines" | "/orders/:id/pick" | "/orders/new" | "/login" | "/stock" | "/stock/:id";
  };
  "routes/purchasing.tsx": {
    id: "routes/purchasing";
    page: "/purchasing" | "/purchasing/:id" | "/purchasing/:id/transition" | "/purchasing/:id/receive" | "/purchasing/:id/lines" | "/purchasing/new";
  };
  "routes/purchasing._index.tsx": {
    id: "routes/purchasing._index";
    page: "/purchasing";
  };
  "routes/purchasing.$id.tsx": {
    id: "routes/purchasing.$id";
    page: "/purchasing/:id" | "/purchasing/:id/transition" | "/purchasing/:id/receive" | "/purchasing/:id/lines";
  };
  "routes/purchasing.$id.transition.tsx": {
    id: "routes/purchasing.$id.transition";
    page: "/purchasing/:id/transition";
  };
  "routes/purchasing.$id.receive.tsx": {
    id: "routes/purchasing.$id.receive";
    page: "/purchasing/:id/receive";
  };
  "routes/purchasing.$id._index.tsx": {
    id: "routes/purchasing.$id._index";
    page: "/purchasing/:id";
  };
  "routes/purchasing.$id.lines.tsx": {
    id: "routes/purchasing.$id.lines";
    page: "/purchasing/:id/lines";
  };
  "routes/purchasing.new.tsx": {
    id: "routes/purchasing.new";
    page: "/purchasing/new";
  };
  "routes/customers.tsx": {
    id: "routes/customers";
    page: "/customers" | "/customers/:id" | "/customers/:id/edit" | "/customers/new";
  };
  "routes/customers._index.tsx": {
    id: "routes/customers._index";
    page: "/customers";
  };
  "routes/customers.$id.tsx": {
    id: "routes/customers.$id";
    page: "/customers/:id" | "/customers/:id/edit";
  };
  "routes/customers.$id._index.tsx": {
    id: "routes/customers.$id._index";
    page: "/customers/:id";
  };
  "routes/customers.$id.edit.tsx": {
    id: "routes/customers.$id.edit";
    page: "/customers/:id/edit";
  };
  "routes/customers.new.tsx": {
    id: "routes/customers.new";
    page: "/customers/new";
  };
  "routes/inventory.tsx": {
    id: "routes/inventory";
    page: "/inventory" | "/inventory/export" | "/inventory/:id" | "/inventory/:id/movements" | "/inventory/:id/edit" | "/inventory/:id/lots" | "/inventory/new";
  };
  "routes/inventory._index.tsx": {
    id: "routes/inventory._index";
    page: "/inventory";
  };
  "routes/inventory.export.tsx": {
    id: "routes/inventory.export";
    page: "/inventory/export";
  };
  "routes/inventory.$id.tsx": {
    id: "routes/inventory.$id";
    page: "/inventory/:id" | "/inventory/:id/movements" | "/inventory/:id/edit" | "/inventory/:id/lots";
  };
  "routes/inventory.$id.movements.tsx": {
    id: "routes/inventory.$id.movements";
    page: "/inventory/:id/movements";
  };
  "routes/inventory.$id._index.tsx": {
    id: "routes/inventory.$id._index";
    page: "/inventory/:id";
  };
  "routes/inventory.$id.edit.tsx": {
    id: "routes/inventory.$id.edit";
    page: "/inventory/:id/edit";
  };
  "routes/inventory.$id.lots.tsx": {
    id: "routes/inventory.$id.lots";
    page: "/inventory/:id/lots";
  };
  "routes/inventory.new.tsx": {
    id: "routes/inventory.new";
    page: "/inventory/new";
  };
  "routes/suppliers.tsx": {
    id: "routes/suppliers";
    page: "/suppliers" | "/suppliers/:id" | "/suppliers/:id/edit" | "/suppliers/new";
  };
  "routes/suppliers._index.tsx": {
    id: "routes/suppliers._index";
    page: "/suppliers";
  };
  "routes/suppliers.$id.tsx": {
    id: "routes/suppliers.$id";
    page: "/suppliers/:id" | "/suppliers/:id/edit";
  };
  "routes/suppliers.$id._index.tsx": {
    id: "routes/suppliers.$id._index";
    page: "/suppliers/:id";
  };
  "routes/suppliers.$id.edit.tsx": {
    id: "routes/suppliers.$id.edit";
    page: "/suppliers/:id/edit";
  };
  "routes/suppliers.new.tsx": {
    id: "routes/suppliers.new";
    page: "/suppliers/new";
  };
  "routes/planning.tsx": {
    id: "routes/planning";
    page: "/planning" | "/planning/purchasing" | "/planning/materials" | "/planning/packaging" | "/planning/schedule" | "/planning/summary" | "/planning/demand";
  };
  "routes/planning.purchasing.tsx": {
    id: "routes/planning.purchasing";
    page: "/planning/purchasing";
  };
  "routes/planning.materials.tsx": {
    id: "routes/planning.materials";
    page: "/planning/materials";
  };
  "routes/planning.packaging.tsx": {
    id: "routes/planning.packaging";
    page: "/planning/packaging";
  };
  "routes/planning.schedule.tsx": {
    id: "routes/planning.schedule";
    page: "/planning/schedule";
  };
  "routes/planning.summary.tsx": {
    id: "routes/planning.summary";
    page: "/planning/summary";
  };
  "routes/planning._index.tsx": {
    id: "routes/planning._index";
    page: "/planning";
  };
  "routes/planning.demand.tsx": {
    id: "routes/planning.demand";
    page: "/planning/demand";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/settings._index.tsx": {
    id: "routes/settings._index";
    page: "/settings";
  };
  "routes/batches.tsx": {
    id: "routes/batches";
    page: "/batches" | "/batches/export" | "/batches/:id" | "/batches/:id/fermentation" | "/batches/:id/consumption" | "/batches/:id/transition" | "/batches/:id/packaging" | "/batches/:id/quality" | "/batches/new";
  };
  "routes/batches._index.tsx": {
    id: "routes/batches._index";
    page: "/batches";
  };
  "routes/batches.export.tsx": {
    id: "routes/batches.export";
    page: "/batches/export";
  };
  "routes/batches.$id.tsx": {
    id: "routes/batches.$id";
    page: "/batches/:id" | "/batches/:id/fermentation" | "/batches/:id/consumption" | "/batches/:id/transition" | "/batches/:id/packaging" | "/batches/:id/quality";
  };
  "routes/batches.$id.fermentation.tsx": {
    id: "routes/batches.$id.fermentation";
    page: "/batches/:id/fermentation";
  };
  "routes/batches.$id.consumption.tsx": {
    id: "routes/batches.$id.consumption";
    page: "/batches/:id/consumption";
  };
  "routes/batches.$id.transition.tsx": {
    id: "routes/batches.$id.transition";
    page: "/batches/:id/transition";
  };
  "routes/batches.$id.packaging.tsx": {
    id: "routes/batches.$id.packaging";
    page: "/batches/:id/packaging";
  };
  "routes/batches.$id.quality.tsx": {
    id: "routes/batches.$id.quality";
    page: "/batches/:id/quality";
  };
  "routes/batches.$id._index.tsx": {
    id: "routes/batches.$id._index";
    page: "/batches/:id";
  };
  "routes/batches.new.tsx": {
    id: "routes/batches.new";
    page: "/batches/new";
  };
  "routes/recipes.tsx": {
    id: "routes/recipes";
    page: "/recipes" | "/recipes/import" | "/recipes/:id" | "/recipes/:id/ingredients" | "/recipes/:id/versions" | "/recipes/:id/process" | "/recipes/:id/clone" | "/recipes/:id/edit" | "/recipes/new";
  };
  "routes/recipes._index.tsx": {
    id: "routes/recipes._index";
    page: "/recipes";
  };
  "routes/recipes.import.tsx": {
    id: "routes/recipes.import";
    page: "/recipes/import";
  };
  "routes/recipes.$id.tsx": {
    id: "routes/recipes.$id";
    page: "/recipes/:id" | "/recipes/:id/ingredients" | "/recipes/:id/versions" | "/recipes/:id/process" | "/recipes/:id/clone" | "/recipes/:id/edit";
  };
  "routes/recipes.$id.ingredients.tsx": {
    id: "routes/recipes.$id.ingredients";
    page: "/recipes/:id/ingredients";
  };
  "routes/recipes.$id.versions.tsx": {
    id: "routes/recipes.$id.versions";
    page: "/recipes/:id/versions";
  };
  "routes/recipes.$id.process.tsx": {
    id: "routes/recipes.$id.process";
    page: "/recipes/:id/process";
  };
  "routes/recipes.$id._index.tsx": {
    id: "routes/recipes.$id._index";
    page: "/recipes/:id";
  };
  "routes/recipes.$id.clone.tsx": {
    id: "routes/recipes.$id.clone";
    page: "/recipes/:id/clone";
  };
  "routes/recipes.$id.edit.tsx": {
    id: "routes/recipes.$id.edit";
    page: "/recipes/:id/edit";
  };
  "routes/recipes.new.tsx": {
    id: "routes/recipes.new";
    page: "/recipes/new";
  };
  "routes/vessels.tsx": {
    id: "routes/vessels";
    page: "/vessels" | "/vessels/:id" | "/vessels/new";
  };
  "routes/vessels._index.tsx": {
    id: "routes/vessels._index";
    page: "/vessels";
  };
  "routes/vessels.$id.tsx": {
    id: "routes/vessels.$id";
    page: "/vessels/:id";
  };
  "routes/vessels.new.tsx": {
    id: "routes/vessels.new";
    page: "/vessels/new";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders" | "/orders/export" | "/orders/:id" | "/orders/:id/transition" | "/orders/:id/invoice" | "/orders/:id/lines" | "/orders/:id/pick" | "/orders/new";
  };
  "routes/orders._index.tsx": {
    id: "routes/orders._index";
    page: "/orders";
  };
  "routes/orders.export.tsx": {
    id: "routes/orders.export";
    page: "/orders/export";
  };
  "routes/orders.$id.tsx": {
    id: "routes/orders.$id";
    page: "/orders/:id" | "/orders/:id/transition" | "/orders/:id/invoice" | "/orders/:id/lines" | "/orders/:id/pick";
  };
  "routes/orders.$id.transition.tsx": {
    id: "routes/orders.$id.transition";
    page: "/orders/:id/transition";
  };
  "routes/orders.$id.invoice.tsx": {
    id: "routes/orders.$id.invoice";
    page: "/orders/:id/invoice";
  };
  "routes/orders.$id._index.tsx": {
    id: "routes/orders.$id._index";
    page: "/orders/:id";
  };
  "routes/orders.$id.lines.tsx": {
    id: "routes/orders.$id.lines";
    page: "/orders/:id/lines";
  };
  "routes/orders.$id.pick.tsx": {
    id: "routes/orders.$id.pick";
    page: "/orders/:id/pick";
  };
  "routes/orders.new.tsx": {
    id: "routes/orders.new";
    page: "/orders/new";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/stock.tsx": {
    id: "routes/stock";
    page: "/stock" | "/stock/:id";
  };
  "routes/stock._index.tsx": {
    id: "routes/stock._index";
    page: "/stock";
  };
  "routes/stock.$id.tsx": {
    id: "routes/stock.$id";
    page: "/stock/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/purchasing": typeof import("./app/routes/purchasing.tsx");
  "routes/purchasing._index": typeof import("./app/routes/purchasing._index.tsx");
  "routes/purchasing.$id": typeof import("./app/routes/purchasing.$id.tsx");
  "routes/purchasing.$id.transition": typeof import("./app/routes/purchasing.$id.transition.tsx");
  "routes/purchasing.$id.receive": typeof import("./app/routes/purchasing.$id.receive.tsx");
  "routes/purchasing.$id._index": typeof import("./app/routes/purchasing.$id._index.tsx");
  "routes/purchasing.$id.lines": typeof import("./app/routes/purchasing.$id.lines.tsx");
  "routes/purchasing.new": typeof import("./app/routes/purchasing.new.tsx");
  "routes/customers": typeof import("./app/routes/customers.tsx");
  "routes/customers._index": typeof import("./app/routes/customers._index.tsx");
  "routes/customers.$id": typeof import("./app/routes/customers.$id.tsx");
  "routes/customers.$id._index": typeof import("./app/routes/customers.$id._index.tsx");
  "routes/customers.$id.edit": typeof import("./app/routes/customers.$id.edit.tsx");
  "routes/customers.new": typeof import("./app/routes/customers.new.tsx");
  "routes/inventory": typeof import("./app/routes/inventory.tsx");
  "routes/inventory._index": typeof import("./app/routes/inventory._index.tsx");
  "routes/inventory.export": typeof import("./app/routes/inventory.export.tsx");
  "routes/inventory.$id": typeof import("./app/routes/inventory.$id.tsx");
  "routes/inventory.$id.movements": typeof import("./app/routes/inventory.$id.movements.tsx");
  "routes/inventory.$id._index": typeof import("./app/routes/inventory.$id._index.tsx");
  "routes/inventory.$id.edit": typeof import("./app/routes/inventory.$id.edit.tsx");
  "routes/inventory.$id.lots": typeof import("./app/routes/inventory.$id.lots.tsx");
  "routes/inventory.new": typeof import("./app/routes/inventory.new.tsx");
  "routes/suppliers": typeof import("./app/routes/suppliers.tsx");
  "routes/suppliers._index": typeof import("./app/routes/suppliers._index.tsx");
  "routes/suppliers.$id": typeof import("./app/routes/suppliers.$id.tsx");
  "routes/suppliers.$id._index": typeof import("./app/routes/suppliers.$id._index.tsx");
  "routes/suppliers.$id.edit": typeof import("./app/routes/suppliers.$id.edit.tsx");
  "routes/suppliers.new": typeof import("./app/routes/suppliers.new.tsx");
  "routes/planning": typeof import("./app/routes/planning.tsx");
  "routes/planning.purchasing": typeof import("./app/routes/planning.purchasing.tsx");
  "routes/planning.materials": typeof import("./app/routes/planning.materials.tsx");
  "routes/planning.packaging": typeof import("./app/routes/planning.packaging.tsx");
  "routes/planning.schedule": typeof import("./app/routes/planning.schedule.tsx");
  "routes/planning.summary": typeof import("./app/routes/planning.summary.tsx");
  "routes/planning._index": typeof import("./app/routes/planning._index.tsx");
  "routes/planning.demand": typeof import("./app/routes/planning.demand.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/settings._index": typeof import("./app/routes/settings._index.tsx");
  "routes/batches": typeof import("./app/routes/batches.tsx");
  "routes/batches._index": typeof import("./app/routes/batches._index.tsx");
  "routes/batches.export": typeof import("./app/routes/batches.export.tsx");
  "routes/batches.$id": typeof import("./app/routes/batches.$id.tsx");
  "routes/batches.$id.fermentation": typeof import("./app/routes/batches.$id.fermentation.tsx");
  "routes/batches.$id.consumption": typeof import("./app/routes/batches.$id.consumption.tsx");
  "routes/batches.$id.transition": typeof import("./app/routes/batches.$id.transition.tsx");
  "routes/batches.$id.packaging": typeof import("./app/routes/batches.$id.packaging.tsx");
  "routes/batches.$id.quality": typeof import("./app/routes/batches.$id.quality.tsx");
  "routes/batches.$id._index": typeof import("./app/routes/batches.$id._index.tsx");
  "routes/batches.new": typeof import("./app/routes/batches.new.tsx");
  "routes/recipes": typeof import("./app/routes/recipes.tsx");
  "routes/recipes._index": typeof import("./app/routes/recipes._index.tsx");
  "routes/recipes.import": typeof import("./app/routes/recipes.import.tsx");
  "routes/recipes.$id": typeof import("./app/routes/recipes.$id.tsx");
  "routes/recipes.$id.ingredients": typeof import("./app/routes/recipes.$id.ingredients.tsx");
  "routes/recipes.$id.versions": typeof import("./app/routes/recipes.$id.versions.tsx");
  "routes/recipes.$id.process": typeof import("./app/routes/recipes.$id.process.tsx");
  "routes/recipes.$id._index": typeof import("./app/routes/recipes.$id._index.tsx");
  "routes/recipes.$id.clone": typeof import("./app/routes/recipes.$id.clone.tsx");
  "routes/recipes.$id.edit": typeof import("./app/routes/recipes.$id.edit.tsx");
  "routes/recipes.new": typeof import("./app/routes/recipes.new.tsx");
  "routes/vessels": typeof import("./app/routes/vessels.tsx");
  "routes/vessels._index": typeof import("./app/routes/vessels._index.tsx");
  "routes/vessels.$id": typeof import("./app/routes/vessels.$id.tsx");
  "routes/vessels.new": typeof import("./app/routes/vessels.new.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/orders._index": typeof import("./app/routes/orders._index.tsx");
  "routes/orders.export": typeof import("./app/routes/orders.export.tsx");
  "routes/orders.$id": typeof import("./app/routes/orders.$id.tsx");
  "routes/orders.$id.transition": typeof import("./app/routes/orders.$id.transition.tsx");
  "routes/orders.$id.invoice": typeof import("./app/routes/orders.$id.invoice.tsx");
  "routes/orders.$id._index": typeof import("./app/routes/orders.$id._index.tsx");
  "routes/orders.$id.lines": typeof import("./app/routes/orders.$id.lines.tsx");
  "routes/orders.$id.pick": typeof import("./app/routes/orders.$id.pick.tsx");
  "routes/orders.new": typeof import("./app/routes/orders.new.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/stock": typeof import("./app/routes/stock.tsx");
  "routes/stock._index": typeof import("./app/routes/stock._index.tsx");
  "routes/stock.$id": typeof import("./app/routes/stock.$id.tsx");
};