// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/inventory/:id": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/movements": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/lots": {
    params: {
      "id": string;
    };
  };
  "/inventory/new": {
    params: {};
  };
  "/planning": {
    params: {};
  };
  "/planning/materials": {
    params: {};
  };
  "/planning/schedule": {
    params: {};
  };
  "/batches": {
    params: {};
  };
  "/batches/:id": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/fermentation": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/consumption": {
    params: {
      "id": string;
    };
  };
  "/batches/:id/transition": {
    params: {
      "id": string;
    };
  };
  "/batches/new": {
    params: {};
  };
  "/recipes": {
    params: {};
  };
  "/recipes/:id": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/ingredients": {
    params: {
      "id": string;
    };
  };
  "/recipes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/recipes/new": {
    params: {};
  };
  "/vessels": {
    params: {};
  };
  "/vessels/:id": {
    params: {
      "id": string;
    };
  };
  "/vessels/new": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/inventory" | "/inventory/:id" | "/inventory/:id/movements" | "/inventory/:id/edit" | "/inventory/:id/lots" | "/inventory/new" | "/planning" | "/planning/materials" | "/planning/schedule" | "/batches" | "/batches/:id" | "/batches/:id/fermentation" | "/batches/:id/consumption" | "/batches/:id/transition" | "/batches/new" | "/recipes" | "/recipes/:id" | "/recipes/:id/ingredients" | "/recipes/:id/edit" | "/recipes/new" | "/vessels" | "/vessels/:id" | "/vessels/new" | "/logout" | "/login";
  };
  "routes/inventory.tsx": {
    id: "routes/inventory";
    page: "/inventory" | "/inventory/:id" | "/inventory/:id/movements" | "/inventory/:id/edit" | "/inventory/:id/lots" | "/inventory/new";
  };
  "routes/inventory._index.tsx": {
    id: "routes/inventory._index";
    page: "/inventory";
  };
  "routes/inventory.$id.tsx": {
    id: "routes/inventory.$id";
    page: "/inventory/:id" | "/inventory/:id/movements" | "/inventory/:id/edit" | "/inventory/:id/lots";
  };
  "routes/inventory.$id.movements.tsx": {
    id: "routes/inventory.$id.movements";
    page: "/inventory/:id/movements";
  };
  "routes/inventory.$id._index.tsx": {
    id: "routes/inventory.$id._index";
    page: "/inventory/:id";
  };
  "routes/inventory.$id.edit.tsx": {
    id: "routes/inventory.$id.edit";
    page: "/inventory/:id/edit";
  };
  "routes/inventory.$id.lots.tsx": {
    id: "routes/inventory.$id.lots";
    page: "/inventory/:id/lots";
  };
  "routes/inventory.new.tsx": {
    id: "routes/inventory.new";
    page: "/inventory/new";
  };
  "routes/planning.tsx": {
    id: "routes/planning";
    page: "/planning" | "/planning/materials" | "/planning/schedule";
  };
  "routes/planning.materials.tsx": {
    id: "routes/planning.materials";
    page: "/planning/materials";
  };
  "routes/planning.schedule.tsx": {
    id: "routes/planning.schedule";
    page: "/planning/schedule";
  };
  "routes/planning._index.tsx": {
    id: "routes/planning._index";
    page: "/planning";
  };
  "routes/batches.tsx": {
    id: "routes/batches";
    page: "/batches" | "/batches/:id" | "/batches/:id/fermentation" | "/batches/:id/consumption" | "/batches/:id/transition" | "/batches/new";
  };
  "routes/batches._index.tsx": {
    id: "routes/batches._index";
    page: "/batches";
  };
  "routes/batches.$id.tsx": {
    id: "routes/batches.$id";
    page: "/batches/:id" | "/batches/:id/fermentation" | "/batches/:id/consumption" | "/batches/:id/transition";
  };
  "routes/batches.$id.fermentation.tsx": {
    id: "routes/batches.$id.fermentation";
    page: "/batches/:id/fermentation";
  };
  "routes/batches.$id.consumption.tsx": {
    id: "routes/batches.$id.consumption";
    page: "/batches/:id/consumption";
  };
  "routes/batches.$id.transition.tsx": {
    id: "routes/batches.$id.transition";
    page: "/batches/:id/transition";
  };
  "routes/batches.$id._index.tsx": {
    id: "routes/batches.$id._index";
    page: "/batches/:id";
  };
  "routes/batches.new.tsx": {
    id: "routes/batches.new";
    page: "/batches/new";
  };
  "routes/recipes.tsx": {
    id: "routes/recipes";
    page: "/recipes" | "/recipes/:id" | "/recipes/:id/ingredients" | "/recipes/:id/edit" | "/recipes/new";
  };
  "routes/recipes._index.tsx": {
    id: "routes/recipes._index";
    page: "/recipes";
  };
  "routes/recipes.$id.tsx": {
    id: "routes/recipes.$id";
    page: "/recipes/:id" | "/recipes/:id/ingredients" | "/recipes/:id/edit";
  };
  "routes/recipes.$id.ingredients.tsx": {
    id: "routes/recipes.$id.ingredients";
    page: "/recipes/:id/ingredients";
  };
  "routes/recipes.$id._index.tsx": {
    id: "routes/recipes.$id._index";
    page: "/recipes/:id";
  };
  "routes/recipes.$id.edit.tsx": {
    id: "routes/recipes.$id.edit";
    page: "/recipes/:id/edit";
  };
  "routes/recipes.new.tsx": {
    id: "routes/recipes.new";
    page: "/recipes/new";
  };
  "routes/vessels.tsx": {
    id: "routes/vessels";
    page: "/vessels" | "/vessels/:id" | "/vessels/new";
  };
  "routes/vessels._index.tsx": {
    id: "routes/vessels._index";
    page: "/vessels";
  };
  "routes/vessels.$id.tsx": {
    id: "routes/vessels.$id";
    page: "/vessels/:id";
  };
  "routes/vessels.new.tsx": {
    id: "routes/vessels.new";
    page: "/vessels/new";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/inventory": typeof import("./app/routes/inventory.tsx");
  "routes/inventory._index": typeof import("./app/routes/inventory._index.tsx");
  "routes/inventory.$id": typeof import("./app/routes/inventory.$id.tsx");
  "routes/inventory.$id.movements": typeof import("./app/routes/inventory.$id.movements.tsx");
  "routes/inventory.$id._index": typeof import("./app/routes/inventory.$id._index.tsx");
  "routes/inventory.$id.edit": typeof import("./app/routes/inventory.$id.edit.tsx");
  "routes/inventory.$id.lots": typeof import("./app/routes/inventory.$id.lots.tsx");
  "routes/inventory.new": typeof import("./app/routes/inventory.new.tsx");
  "routes/planning": typeof import("./app/routes/planning.tsx");
  "routes/planning.materials": typeof import("./app/routes/planning.materials.tsx");
  "routes/planning.schedule": typeof import("./app/routes/planning.schedule.tsx");
  "routes/planning._index": typeof import("./app/routes/planning._index.tsx");
  "routes/batches": typeof import("./app/routes/batches.tsx");
  "routes/batches._index": typeof import("./app/routes/batches._index.tsx");
  "routes/batches.$id": typeof import("./app/routes/batches.$id.tsx");
  "routes/batches.$id.fermentation": typeof import("./app/routes/batches.$id.fermentation.tsx");
  "routes/batches.$id.consumption": typeof import("./app/routes/batches.$id.consumption.tsx");
  "routes/batches.$id.transition": typeof import("./app/routes/batches.$id.transition.tsx");
  "routes/batches.$id._index": typeof import("./app/routes/batches.$id._index.tsx");
  "routes/batches.new": typeof import("./app/routes/batches.new.tsx");
  "routes/recipes": typeof import("./app/routes/recipes.tsx");
  "routes/recipes._index": typeof import("./app/routes/recipes._index.tsx");
  "routes/recipes.$id": typeof import("./app/routes/recipes.$id.tsx");
  "routes/recipes.$id.ingredients": typeof import("./app/routes/recipes.$id.ingredients.tsx");
  "routes/recipes.$id._index": typeof import("./app/routes/recipes.$id._index.tsx");
  "routes/recipes.$id.edit": typeof import("./app/routes/recipes.$id.edit.tsx");
  "routes/recipes.new": typeof import("./app/routes/recipes.new.tsx");
  "routes/vessels": typeof import("./app/routes/vessels.tsx");
  "routes/vessels._index": typeof import("./app/routes/vessels._index.tsx");
  "routes/vessels.$id": typeof import("./app/routes/vessels.$id.tsx");
  "routes/vessels.new": typeof import("./app/routes/vessels.new.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};